spring.application.name=sales-service

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

service.external.api.rickmorty.url=https://rickandmortyapi.com/api

common.headers.tenantId=DHBO


spring.cloud.openfeign.circuitbreaker.enabled=true

# -------- RESILIENCE4J CIRCUIT BREAKERS --------
resilience4j.circuitbreaker.instances.users-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.users-service.slidingWindowSize=3
resilience4j.circuitbreaker.instances.users-service.failureRateThreshold=30
resilience4j.circuitbreaker.instances.users-service.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.stock-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.stock-service.slidingWindowSize=5
resilience4j.circuitbreaker.instances.stock-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.stock-service.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.notifications-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.notifications-service.slidingWindowSize=5
resilience4j.circuitbreaker.instances.notifications-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notifications-service.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.rickmorty-api.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.rickmorty-api.slidingWindowSize=5
resilience4j.circuitbreaker.instances.rickmorty-api.failureRateThreshold=50
resilience4j.circuitbreaker.instances.rickmorty-api.waitDurationInOpenState=10s